// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc253.cimControl.subsystems;

import org.usfirst.frc253.cimControl.RobotMap;
import edu.wpi.first.wpilibj.SpeedController;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class cimMotors extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController cim1 = RobotMap.cimMotorscim1;
    private final SpeedController cim2 = RobotMap.cimMotorscim2;
    private final SpeedController cim3 = RobotMap.cimMotorscim3;
    private final SpeedController cim4 = RobotMap.cimMotorscim4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public cimMotors(){
    	super();
    	actCim1();
    	actCim2();
    	actCim3();
    	actCim4();
    	stopCim1();
    	stopCim2();
    	stopCim3();
    	stopCim4();
    }
    public void actCim1(){
    	cim1.set(0.25);
    }
    public void actCim2(){
    	cim2.set(0.25);
    }
    public void actCim3(){
    	cim3.set(0.25);
    }
    public void actCim4(){
    	cim4.set(0.25);
    }
    public void stopCim1(){
    	cim1.set(0.00);
    }
    public void stopCim2(){
    	cim2.set(0.00);
    }
    public void stopCim3(){
    	cim3.set(0.00);
    }
    public void stopCim4(){
    	cim4.set(0.00);
    }
    
}

